#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    leftLineFollower, sensorLineFollower)
#pragma config(Sensor, in2,    centerLineFollower, sensorLineFollower)
#pragma config(Sensor, in3,    rightLineFollower, sensorLineFollower)
#pragma config(Sensor, in6,    gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  piston1,        sensorDigitalOut)
#pragma config(Sensor, dgtl2,  piston2,        sensorDigitalOut)
#pragma config(Sensor, I2C_1,  rightIME,       sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_2,  leftIME,        sensorQuadEncoderOnI2CPort,    , AutoAssign)
#pragma config(Sensor, I2C_3,  armIME,         sensorNone)
#pragma config(Motor,  port1,           baseArrGauche, tmotorVex393_HBridge, openLoop, reversed, driveLeft)
#pragma config(Motor,  port2,           baseAvGauche,  tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port3,           ElevAvGauche,  tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           ElevArrGauche, tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           PelleDroite,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           PelleGauche,   tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           ElevArrDroit,  tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           ElevAvDroit,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           baseAvdroit,   tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port10,          baseArrDroit,  tmotorVex393_HBridge, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	repeat (forever) {
		joystickControl(baseAvdroit, Ch2, 10);
		joystickControl(baseArrDroit, Ch2, 10);
		joystickControl(baseAvGauche, Ch3, 10);
		joystickControl(baseArrGauche, Ch3, 10);
		armControl(ElevAvDroit, Btn5U, Btn5D, 75);
		armControl(ElevArrDroit, Btn5U, Btn5D, 75);
		armControl(ElevArrGauche, Btn5U, Btn5D, 75);
		armControl(ElevAvGauche, Btn5U, Btn5D, 75);
		armControl(PelleDroite, Btn6U, Btn6D, 75);
		armControl(PelleGauche, Btn6U, Btn6D, 75);

		if (vexRT[Btn8D] == 1)
    {
      SensorValue[piston1]= 1; //activer les pistons
			SensorValue[piston2]= 1;
			time1[timer1]=0;//remetttre a 0 le compteur de temps
    }
    //si le temps est plus grand que un quart de seconde,desactive les pistons
    if (time1[timer1]>250)
    {
    	SensorValue[piston2]= 0;
    	SensorValue[piston1]= 0;
    }





	} // fin de boucle

}
